wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709811780.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      - 24
      4: 3.10.13
      5: 0.16.4
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
